name: login_flutter
description: A flutter login model app.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10
  firebase_database: ^10.4.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  motion_tab_bar: ^2.0.4
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.2.6
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^17.0.1
  awesome_notifications: ^0.9.3+1
  shared_preferences: ^2.2.3
  animated_text_kit: ^4.2.2
  google_fonts: ^6.2.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/Designer.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/assil.jpg"
    - "assets/rim.jpg"
    - "assets/gaz.gif"
